name: JJCE-Network-Core
authors: Joshua Sing
version: 1.5
main: com.jjce.core

softdepend: [Vault]

commands:
  core:
    description: JJCE-Network-Core Admin Command
    aliases: [jjcecore]
    usage: |
      /core
    permission: core.admin
  core-status:
    description: JJCE-Network-Core Admin Command
    aliases: [jjcestatus]
    usage: |
      /core-status
    permission: core.status

permissions:
  core.status:
    description: JJCE-Network-Core Admin Command
    default: op
  core.admin:
    description: JJCE-Network-Core Admin Command
    default: op
